/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Books
         * @description Liste paginee des LibraryItem de l'utilisateur courant (SQL limit/offset).
         */
        get: operations["list_books_api_v1_books_get"];
        put?: never;
        /**
         * Add Book
         * @description Ajoute un livre a la bibliotheque, soit via un connecteur (`source` +
         *     `result_id`), soit via un fichier deja possede par l'utilisateur
         *     (`file`, multipart). Exactement l'un des deux doit etre fourni.
         *
         *     La branche multipart est **deprecated** : preferer `POST /api/v1/books/upload`
         *     (conservee 1–2 releases pour compatibilite).
         */
        post: operations["add_book_api_v1_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Books */
        post: operations["search_books_api_v1_books_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload d'un ebook
         * @description Importe un fichier ebook (multipart `file`) dans la bibliotheque.
         *
         *     Accepte l'auth utilisateur (Bearer Clerk / `X-Dev-User`) ou la cle
         *     gateway (`X-Gateway-Key`) pour un import au nom du proprio.
         */
        post: operations["upload_book_api_v1_books_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Book */
        delete: operations["delete_book_api_v1_books__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Book */
        patch: operations["update_book_api_v1_books__item_id__patch"];
        trace?: never;
    };
    "/api/v1/books/{item_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Book Deliveries */
        get: operations["list_book_deliveries_api_v1_books__item_id__deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/covers/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cover
         * @description Sert la couverture d'un item possede, telechargee et mise en cache cote serveur.
         */
        get: operations["get_cover_api_v1_covers__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deliveries */
        get: operations["list_deliveries_api_v1_deliveries_get"];
        put?: never;
        /** Create Delivery */
        post: operations["create_delivery_api_v1_deliveries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Delivery */
        get: operations["get_delivery_api_v1_deliveries__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        /**
         * Create Device
         * @description Crée un Device pour l'utilisateur ; calcule delivery_tier selon la marque/modèle.
         */
        post: operations["create_device_api_v1_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device
         * @description Detail d'un device (polling post-liaison cloud).
         */
        get: operations["get_device_api_v1_devices__device_id__get"];
        put?: never;
        post?: never;
        /** Delete Device */
        delete: operations["delete_device_api_v1_devices__device_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Device
         * @description Met a jour le nom/marque/modele/profil d'un device ; recalcule delivery_tier
         *     si la marque ou le modele changent (jamais choisi a la main).
         */
        patch: operations["update_device_api_v1_devices__device_id__patch"];
        trace?: never;
    };
    "/api/v1/devices/{device_id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Link Url
         * @description URL d'autorisation OAuth a afficher a l'utilisateur pour relier son
         *     Dropbox/Google Drive a ce device.
         */
        get: operations["get_link_url_api_v1_devices__device_id__link_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/link/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Link Callback Get
         * @description Callback OAuth public (navigateur) : valide `state`, echange `code`,
         *     redirige vers le dashboard. Sans auth Clerk — le `state` signe + store
         *     serveur prouve l'intention de liaison.
         *
         *     Les echecs (refus fournisseur, state absent/invalide, device supprime,
         *     echange refuse) redirigent toujours vers le dashboard avec
         *     `cloud_link=error` — jamais une page d'erreur API dans le navigateur.
         */
        get: operations["link_callback_get_api_v1_devices__device_id__link_callback_get"];
        put?: never;
        /**
         * Link Callback
         * @description Echange le code OAuth contre un token et le stocke chiffre (API auth).
         *
         *     Conserve pour clients API ; le parcours UI passe par le GET public + state.
         */
        post: operations["link_callback_api_v1_devices__device_id__link_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Delivery Methods
         * @description Modes de livraison candidats pour ce device (email/dropbox/drive/
         *     browser_code), chacun avec sa disponibilite reelle : le frontend s'en
         *     sert pour proposer uniquement les modes utilisables au lieu de laisser
         *     choisir un tier technique A/B/C/D a la main.
         */
        get: operations["get_delivery_methods_api_v1_devices__device_id__methods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Gateways */
        get: operations["list_gateways_api_v1_gateways_get"];
        put?: never;
        /** Create Gateway */
        post: operations["create_gateway_api_v1_gateways_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gateway Job Status */
        get: operations["get_gateway_job_status_api_v1_gateways_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/jobs/{job_id}/fetch-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Fetch Result */
        post: operations["submit_fetch_result_api_v1_gateways_jobs__job_id__fetch_result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/jobs/{job_id}/search-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Search Results */
        post: operations["submit_search_results_api_v1_gateways_jobs__job_id__search_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pair Gateway */
        post: operations["pair_gateway_api_v1_gateways_pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll Gateway */
        post: operations["poll_gateway_api_v1_gateways_poll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Gateway */
        post: operations["revoke_gateway_api_v1_gateways_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/{gateway_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Gateway */
        delete: operations["delete_gateway_api_v1_gateways__gateway_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/{gateway_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Gateway Jobs */
        get: operations["list_gateway_jobs_api_v1_gateways__gateway_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/{gateway_id}/recreate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recreate Gateway
         * @description Regenere le code de connexion et la cle d'acces (affichage unique).
         */
        post: operations["recreate_gateway_api_v1_gateways__gateway_id__recreate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opds/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opds Tokens */
        get: operations["list_opds_tokens_api_v1_opds_tokens_get"];
        put?: never;
        /** Create Opds Token */
        post: operations["create_opds_token_api_v1_opds_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opds/tokens/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Opds Token */
        post: operations["revoke_opds_token_api_v1_opds_tokens_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["update_source_api_v1_sources__source_id__patch"];
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/c/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog Page */
        get: operations["get_catalog_page_c__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/c/{code}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_c__code__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Sante + capacite de conversion (ebook-convert), verifiable sans logs.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opds/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opds Root */
        get: operations["opds_root_opds__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opds/{token}/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opds All */
        get: operations["opds_all_opds__token__all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opds/{token}/author": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opds By Author */
        get: operations["opds_by_author_opds__token__author_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opds/{token}/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opds Authors */
        get: operations["opds_authors_opds__token__authors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opds/{token}/cover/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opds Cover */
        get: operations["opds_cover_opds__token__cover__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opds/{token}/download/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opds Download */
        get: operations["opds_download_opds__token__download__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opds/{token}/opensearch.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opds Opensearch */
        get: operations["opds_opensearch_opds__token__opensearch_xml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opds/{token}/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opds Recent */
        get: operations["opds_recent_opds__token__recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opds/{token}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opds Search */
        get: operations["opds_search_opds__token__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_submit_fetch_result_api_v1_gateways_jobs__job_id__fetch_result_post */
        Body_submit_fetch_result_api_v1_gateways_jobs__job_id__fetch_result_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_book_api_v1_books_upload_post */
        Body_upload_book_api_v1_books_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** DeliveryCreate */
        DeliveryCreate: {
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Format */
            format?: ("epub" | "mobi" | "azw3" | "pdf") | null;
            /**
             * Library Item Id
             * Format: uuid
             */
            library_item_id: string;
            /** @default email */
            method: components["schemas"]["DeliveryMethod"];
        };
        /**
         * DeliveryMethod
         * @enum {string}
         */
        DeliveryMethod: "email" | "dropbox" | "drive" | "browser_code" | "usb";
        /** DeliveryOut */
        DeliveryOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Delivered At */
            delivered_at: string | null;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Device Label */
            device_label?: string | null;
            /** Download Url */
            download_url?: string | null;
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Item Author */
            item_author?: string | null;
            /** Item Title */
            item_title?: string | null;
            /** Library Item Id */
            library_item_id?: string | null;
            method: components["schemas"]["DeliveryMethod"];
            status: components["schemas"]["DeliveryStatus"];
            /** Target Format */
            target_format?: string | null;
        };
        /**
         * DeliveryStatus
         * @enum {string}
         */
        DeliveryStatus: "queued" | "sent" | "delivered" | "failed";
        /**
         * DeliveryTier
         * @enum {string}
         */
        DeliveryTier: "A" | "B" | "C" | "D";
        /**
         * DeviceBrand
         * @enum {string}
         */
        DeviceBrand: "kindle" | "kobo" | "tolino" | "pocketbook" | "other";
        /**
         * DeviceCreate
         * @description Pas de `delivery_tier` ici : le tier est toujours calcule cote serveur
         *     depuis `brand`/`model` (voir `api.devices._compute_tier`), jamais choisi
         *     a la main par le client (extra fields ignores par defaut par pydantic).
         */
        DeviceCreate: {
            brand: components["schemas"]["DeviceBrand"];
            /** Conversion Profile */
            conversion_profile?: ("reader_6in" | "reader_7in_plus" | "tablet") | null;
            /** Model */
            model?: string | null;
            /** Name */
            name?: string | null;
        };
        /** DeviceLinkCallback */
        DeviceLinkCallback: {
            /** Code */
            code: string;
            /** Provider */
            provider: string;
        };
        /** DeviceLinkUrlOut */
        DeviceLinkUrlOut: {
            /** Url */
            url: string;
        };
        /** DeviceOut */
        DeviceOut: {
            brand: components["schemas"]["DeviceBrand"];
            /**
             * Cloud Linked
             * @default false
             */
            cloud_linked: boolean;
            /** Cloud Provider */
            cloud_provider?: ("dropbox" | "drive") | null;
            /** Conversion Profile */
            conversion_profile?: ("reader_6in" | "reader_7in_plus" | "tablet") | null;
            delivery_tier: components["schemas"]["DeliveryTier"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Model */
            model: string | null;
            /** Name */
            name: string | null;
        };
        /** DevicePatch */
        DevicePatch: {
            brand?: components["schemas"]["DeviceBrand"] | null;
            /** Conversion Profile */
            conversion_profile?: ("reader_6in" | "reader_7in_plus" | "tablet") | null;
            /** Model */
            model?: string | null;
            /** Name */
            name?: string | null;
        };
        /** GatewayCreate */
        GatewayCreate: {
            /**
             * Name
             * @default Gateway
             */
            name: string;
        };
        /** GatewayCredentials */
        GatewayCredentials: {
            /**
             * Gateway Id
             * Format: uuid
             */
            gateway_id: string;
            /** Gateway Key */
            gateway_key: string;
            /**
             * Gateway Online Seconds
             * @default 60
             */
            gateway_online_seconds: number;
            /** Pairing Expires At */
            pairing_expires_at?: string | null;
            /** Pairing Token */
            pairing_token: string;
            /**
             * Pairing Token Ttl Minutes
             * @default 15
             */
            pairing_token_ttl_minutes: number;
        };
        /** GatewayFetchQueued */
        GatewayFetchQueued: {
            /**
             * Gateway Job Id
             * Format: uuid
             */
            gateway_job_id: string;
            status: components["schemas"]["GatewayJobStatus"];
        };
        /** GatewayFetchResult */
        GatewayFetchResult: {
            /**
             * Library Item Id
             * Format: uuid
             */
            library_item_id: string;
        };
        /** GatewayId */
        GatewayId: {
            /**
             * Gateway Id
             * Format: uuid
             */
            gateway_id: string;
        };
        /** GatewayJobAck */
        GatewayJobAck: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            status: components["schemas"]["GatewayJobStatus"];
        };
        /** GatewayJobOut */
        GatewayJobOut: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Payload */
            payload: Record<string, never>;
            status: components["schemas"]["GatewayJobStatus"];
            type: components["schemas"]["GatewayJobType"];
        };
        /**
         * GatewayJobStatus
         * @enum {string}
         */
        GatewayJobStatus: "pending" | "queued" | "running" | "done" | "failed";
        /** GatewayJobStatusOut */
        GatewayJobStatusOut: {
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Error */
            error?: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Library Item Id */
            library_item_id?: string | null;
            /** Payload */
            payload: Record<string, never>;
            status: components["schemas"]["GatewayJobStatus"];
            type: components["schemas"]["GatewayJobType"];
        };
        /**
         * GatewayJobType
         * @enum {string}
         */
        GatewayJobType: "search" | "fetch";
        /** GatewayOut */
        GatewayOut: {
            /**
             * Gateway Id
             * Format: uuid
             */
            gateway_id: string;
            /**
             * Gateway Online Seconds
             * @default 60
             */
            gateway_online_seconds: number;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Name */
            name: string;
            /** Pairing Expires At */
            pairing_expires_at?: string | null;
            /**
             * Pairing Token Ttl Minutes
             * @default 15
             */
            pairing_token_ttl_minutes: number;
            status: components["schemas"]["PairingStatus"];
        };
        /** GatewayPair */
        GatewayPair: {
            /** Pairing Token */
            pairing_token: string;
        };
        /** GatewayRevoke */
        GatewayRevoke: {
            /**
             * Gateway Id
             * Format: uuid
             */
            gateway_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LibraryItemOut */
        LibraryItemOut: {
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Author */
            author: string;
            /** Cover Url */
            cover_url: string | null;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isbn */
            isbn?: string | null;
            /** Language */
            language?: string | null;
            /** Original Format */
            original_format: string;
            /** Page Count */
            page_count?: number | null;
            /** Published Year */
            published_year?: number | null;
            /** Publisher */
            publisher?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Source Id */
            source_id: string | null;
            /** Source Ref */
            source_ref?: string | null;
            /** Title */
            title: string;
        };
        /** LibraryItemUpdate */
        LibraryItemUpdate: {
            /** Author */
            author?: string | null;
            /** Description */
            description?: string | null;
            /** Isbn */
            isbn?: string | null;
            /** Language */
            language?: string | null;
            /** Page Count */
            page_count?: number | null;
            /** Published Year */
            published_year?: number | null;
            /** Publisher */
            publisher?: string | null;
            /** Title */
            title?: string | null;
        };
        /** MethodAvailability */
        MethodAvailability: {
            /** Available */
            available: boolean;
            method: components["schemas"]["DeliveryMethod"];
            /** Reason Code */
            reason_code?: string | null;
        };
        /** OpdsTokenCreate */
        OpdsTokenCreate: {
            /**
             * Label
             * @default Liseuse
             */
            label: string;
        };
        /** OpdsTokenCreated */
        OpdsTokenCreated: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Token */
            token: string;
            /** Url */
            url: string;
        };
        /** OpdsTokenOut */
        OpdsTokenOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Last Used At */
            last_used_at: string | null;
        };
        /** OpdsTokenRevoke */
        OpdsTokenRevoke: {
            /**
             * Token Id
             * Format: uuid
             */
            token_id: string;
        };
        /** PaginatedLibraryItems */
        PaginatedLibraryItems: {
            /** Items */
            items: components["schemas"]["LibraryItemOut"][];
            /** Limit */
            limit: number;
            /** Page */
            page: number;
            /** Total */
            total: number;
        };
        /**
         * PairingStatus
         * @enum {string}
         */
        PairingStatus: "pending" | "paired" | "revoked";
        /** Result */
        Result: {
            /**
             * Author
             * @default
             */
            author: string;
            /** Cover Url */
            cover_url?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Format
             * @default epub
             */
            format: string;
            /** Guid */
            guid?: string | null;
            /** Indexer Id */
            indexer_id?: number | string | null;
            /** Isbn */
            isbn?: string | null;
            /** Language */
            language?: string | null;
            /** Magnet Url */
            magnet_url?: string | null;
            /** Page Count */
            page_count?: number | null;
            /** Result Id */
            result_id: string;
            /** Seeders */
            seeders?: number | null;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /** ResultOut */
        ResultOut: {
            /**
             * Author
             * @default
             */
            author: string;
            /** Cover Url */
            cover_url?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Format
             * @default epub
             */
            format: string;
            /** Guid */
            guid?: string | null;
            /** Indexer Id */
            indexer_id?: number | string | null;
            /** Isbn */
            isbn?: string | null;
            /** Language */
            language?: string | null;
            /** Magnet Url */
            magnet_url?: string | null;
            /**
             * Owned
             * @default false
             */
            owned: boolean;
            /** Page Count */
            page_count?: number | null;
            /** Result Id */
            result_id: string;
            /** Seeders */
            seeders?: number | null;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /** Scope */
            scope?: string[] | null;
        };
        /**
         * SearchResults
         * @description Liste JSON nue acceptee depuis le gateway-agent.
         */
        SearchResults: components["schemas"]["Result"][];
        /** SourceOut */
        SourceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
        };
        /** SourceUpdate */
        SourceUpdate: {
            /** Enabled */
            enabled: boolean;
        };
        /** UserOut */
        UserOut: {
            /** Default Format */
            default_format: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kindle Email */
            kindle_email: string | null;
        };
        /** UserPatch */
        UserPatch: {
            /** Default Format */
            default_format?: ("epub" | "mobi" | "azw3" | "pdf") | null;
            /** Kindle Email */
            kindle_email?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_books_api_v1_books_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLibraryItems"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_book_api_v1_books_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemOut"] | components["schemas"]["GatewayFetchQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_books_api_v1_books_search_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_book_api_v1_books_upload_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
                "X-Gateway-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_book_api_v1_books_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_book_api_v1_books__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_book_api_v1_books__item_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_book_deliveries_api_v1_books__item_id__deliveries_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cover_api_v1_covers__item_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deliveries_api_v1_deliveries_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_delivery_api_v1_deliveries_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_delivery_api_v1_deliveries__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device_api_v1_devices_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_v1_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_api_v1_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_api_v1_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevicePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_link_url_api_v1_devices__device_id__link_get: {
        parameters: {
            query: {
                provider: string;
                locale?: string | null;
            };
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLinkUrlOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_callback_get_api_v1_devices__device_id__link_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_callback_api_v1_devices__device_id__link_callback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceLinkCallback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_delivery_methods_api_v1_devices__device_id__methods_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodAvailability"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gateways_api_v1_gateways_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_gateway_api_v1_gateways_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GatewayCreate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayCredentials"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gateway_job_status_api_v1_gateways_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayJobStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_fetch_result_api_v1_gateways_jobs__job_id__fetch_result_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Gateway-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_fetch_result_api_v1_gateways_jobs__job_id__fetch_result_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayFetchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_search_results_api_v1_gateways_jobs__job_id__search_results_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Gateway-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchResults"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayJobAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_gateway_api_v1_gateways_pair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayPair"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayId"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_gateway_api_v1_gateways_poll_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Gateway-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayJobOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_gateway_api_v1_gateways_revoke_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayRevoke"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayId"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_gateway_api_v1_gateways__gateway_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                gateway_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gateway_jobs_api_v1_gateways__gateway_id__jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                gateway_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayJobStatusOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recreate_gateway_api_v1_gateways__gateway_id__recreate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                gateway_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayCredentials"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opds_tokens_api_v1_opds_tokens_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpdsTokenOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_opds_token_api_v1_opds_tokens_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OpdsTokenCreate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpdsTokenCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_opds_token_api_v1_opds_tokens_revoke_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpdsTokenRevoke"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpdsTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_v1_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Dev-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog_page_c__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_c__code__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    opds_root_opds__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opds_all_opds__token__all_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opds_by_author_opds__token__author_get: {
        parameters: {
            query: {
                name: string;
                page?: number;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opds_authors_opds__token__authors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opds_cover_opds__token__cover__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opds_download_opds__token__download__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opds_opensearch_opds__token__opensearch_xml_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opds_recent_opds__token__recent_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opds_search_opds__token__search_get: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
